Feature/rhino object functions
compas-dev/compas pull request #256
Opened 2019-02-18 21:54 UTC by robin-oval

Rhino curve and surface functions
curve length and is_closed
surface kinks, closest_point, closest_point_on_boundary and several mapping/remapping functions between XYZ and UV(0) spaces based on the surface's parameterisation

2019-02-25 13:01 UTC, tomvanmele requested changes
we should avoid just providing wrappers to the corresponding rs.xxx functions and use RhinoCommon object methods where possible...

it is not entirely clear what some of the functions actually do, so examples and more explanations are necessary...

2019-02-25 13:01 UTC, tomvanmele commented on src/compas_rhino/geometry/curve.py
> +        return rs.CurveLength(self.guid)
the object is also stored, and there is a method of the object for getting the length...
https://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Geometry_Curve_GetLength_2.htm

2019-02-25 13:01 UTC, tomvanmele commented on src/compas_rhino/geometry/curve.py
> +        return rs.IsCurveClosed(self.guid)
same comment
https://developer.rhino3d.com/api/RhinoCommon/html/P_Rhino_Geometry_Curve_IsClosed.htm

2019-02-25 13:01 UTC, tomvanmele commented on src/compas_rhino/geometry/surface.py
> +
remove empty line

2019-02-25 13:01 UTC, tomvanmele commented on src/compas_rhino/geometry/surface.py
> +        borders = self.borders(type = 0)
spaces

2019-02-25 13:01 UTC, tomvanmele commented on src/compas_rhino/geometry/surface.py
> +        return min(proj_dist, key = proj_dist.get)
spaces

2019-02-25 13:01 UTC, tomvanmele commented on src/compas_rhino/geometry/surface.py
> +        return rs.SurfaceClosestPoint(self.guid, xyz) + (0.,)
not sure i understand what this function does

2019-02-25 13:01 UTC, tomvanmele commented on src/compas_rhino/geometry/surface.py
> +
blank line

2019-02-25 13:01 UTC, tomvanmele commented on src/compas_rhino/geometry/surface.py
> +        return rs.SurfaceClosestPoint(self.guid, xyz) + (0.,)
blank line

2019-02-25 13:01 UTC, tomvanmele commented on src/compas_rhino/geometry/surface.py
> +
blank line

2019-02-25 13:01 UTC, tomvanmele commented on src/compas_rhino/geometry/surface.py
> +
blank line

2019-02-25 13:01 UTC, tomvanmele commented on src/compas_rhino/geometry/surface.py
> +    def remap_xyz_point(self, uv):
example?

2019-02-25 13:01 UTC, tomvanmele commented on src/compas_rhino/geometry/surface.py
> +            List of UV(0) coordinates.
UV(0)

2019-03-07 16:06 UTC, robin-oval commented
instead of wrapping rhinoscriptsyntax functions, is it better to wrap RhinoCommon functions or not wrapping anything and calling RhinoCommon methods directly?

2019-03-12 10:01 UTC, tomvanmele approved these changes

2019-03-14 11:17 UTC, merged