updating volmesh and restructuring halffaces as lists
compas-dev/compas pull request #283
Opened 2019-05-02 13:39 UTC by juney-lee

- various updates and clean up of the volmesh class (ongoing and more to come...)
- halffaces are restructured as list of vertex keys (like the faces of a mesh)

2019-05-02 14:46 UTC, gonzalocasas commented
@juney-lee if possible, please don't delete the template of the PR, and instead use it to tick the type of change you're suggesting. Also, pls add an entry to the `CHANGELOG.md` file ;)

2019-05-03 06:20 UTC, tomvanmele requested changes
the implementation should be equivalent with the other data structures.
* use iterators for all accessor functions
* all data should be accessible through methods

2019-05-03 06:20 UTC, brgcode commented on src/compas/datastructures/volmesh/volmesh.py
> +        edge_attr = self.default_edge_attributes
this should be a copy

2019-05-03 06:20 UTC, brgcode commented on src/compas/datastructures/volmesh/volmesh.py
>          for fkey in self.halfface:
should this not be `for fkey in self.halffaces()`

2019-05-03 06:20 UTC, brgcode commented on src/compas/datastructures/volmesh/volmesh.py
>          for fkey in self.halfface:
is there such a thing as `self.halffaces()`?

2019-05-06 14:55 UTC, closed without merging