first pull for testing
compas-dev/compas pull request #322
Opened 2019-09-12 10:39 UTC by Licini

1. fixed two test warnings because of python deprecations

2. moved the current test files under `test/compas` folder to mirror the file structure from `src/`, so later we can also have `test/compas_rhino`, `test/compas_blender` etc

1. completed test script for `compas.geometry.bbox` functions

2019-09-12 11:22 UTC, gonzalocasas commented
Most model tests are broken now

2019-09-12 11:26 UTC, gonzalocasas requested changes
The change still needs some work, it breaks on python 2 (python death clock is ticking but is not dead yet) ~, and I'm not sure about the moved files, I don't see that you updated the loading of them so I would assume they are not working either (?) I didn't check this thou, I might be wrong.~

2019-09-12 11:26 UTC, gonzalocasas commented on src/compas/files/urdf.py
> +        argspec = inspect.getfullargspec(type.__init__)
I think this doesn't work on python 2

2019-09-12 14:56 UTC, Licini commented on src/compas/files/urdf.py
> +        argspec = inspect.getfullargspec(type.__init__)
Hi Gonzalo, thanks for the review. yep, was fully aware we will still use 2.7. Will make change regarding to this part

2019-09-12 15:05 UTC, Licini commented on src/compas/files/urdf.py
> +        argspec = inspect.getfullargspec(type.__init__)
Also regarding to moved files,  would you mind to point out what/where is the loading you are referring to? I'm under the impression everything is being detected automatically when put under `test/` folder, and I was able to execute and pass these test after moving(only with 3.7 though). First day working on COMPAS code base, still getting familiar on everything : )

2019-09-13 06:57 UTC, gonzalocasas commented on src/compas/files/urdf.py
> +        argspec = inspect.getfullargspec(type.__init__)
You are correct, sorry! I missed the fact that you moved the entirely of the test + fixtures one level deeper.

2019-09-16 08:20 UTC, Licini commented on src/compas/files/urdf.py
> +        argspec = inspect.getfullargspec(type.__init__)
added a detector, now it will use old code for python2.7

2019-09-16 08:22 UTC, brgcode commented
@gonzalocasas all good now?

2019-09-16 11:58 UTC, merged