add capsule, some typos, separate checks u and v
compas-dev/compas pull request #374
Opened 2019-10-29 10:04 UTC by worbit

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.

As discussed, add the `Capsule` class, will add unimplemented methods (eg `to_vertices_and_faces`)

2019-10-30 08:00 UTC, tomvanmele reviewed
i guess the only thing left to do is the caps?

2019-10-30 08:00 UTC, tomvanmele commented on src/compas/geometry/primitives/shapes/capsule.py
> +        # [point,point] or ...
what is all this for?

2019-10-30 08:00 UTC, tomvanmele commented on src/compas/geometry/primitives/shapes/capsule.py
> +    pass
end with newline...

2019-10-30 09:20 UTC, worbit commented on src/compas/geometry/primitives/shapes/capsule.py
> +        # [point,point] or ...
thanks for reminding me, this is a leftover from before i used a `Line` object for the `Capsule` axis

2019-10-30 14:03 UTC, romanarust requested changes
docstrings and examples missing here and there

2019-10-30 14:03 UTC, romanarust commented on src/compas/geometry/primitives/shapes/capsule.py
> +        matrix : list of list
Shouldn't this be rather a :class:`Transformation` than the pure matrix?

2019-10-30 14:03 UTC, romanarust commented on src/compas/geometry/primitives/shapes/capsule.py
> +        Capsule
```suggestion
:class:`Capsule`
```

2019-10-30 14:03 UTC, romanarust commented on src/compas/geometry/primitives/line.py
>      def transform(self, matrix):
shouldn't this be rather a :class:`Transformation`?

2019-10-30 14:03 UTC, romanarust commented on src/compas/geometry/primitives/shapes/capsule.py
> +    def transform(self, matrix):
```suggestion
    def transform(self, transformation):
```

2019-10-30 14:03 UTC, romanarust commented on src/compas/geometry/primitives/shapes/capsule.py
> +    >>> TODO
```suggestion
    >>> line = Line((1, 2, 3), (5, 4, 3))
    >>> capsule = Capsule(line, 1.2)
```

2019-10-30 14:03 UTC, romanarust commented on src/compas/geometry/primitives/shapes/capsule.py
> +
what about a `__repr__` that returns a string that can be used to construct a Capsule again, like:
```suggestion
    def __repr__(self):
        return "Capsule({0}, {1})".format(self.line, self.radius)
```

2019-10-31 14:01 UTC, tomvanmele commented on src/compas/geometry/primitives/line.py
>      def transform(self, matrix):
yes indeed

2019-10-31 14:01 UTC, tomvanmele commented on src/compas/geometry/primitives/shapes/capsule.py
> +
does `repr` get applied recursively? i mean, will this apply `repr` to `self.line` as well?

2019-10-31 14:01 UTC, tomvanmele commented on src/compas/geometry/primitives/shapes/capsule.py
> +    def transform(self, matrix):
agreed

2019-10-31 14:01 UTC, tomvanmele commented on src/compas/geometry/primitives/shapes/capsule.py
> +        matrix : list of list
yes indeed

2019-10-31 14:01 UTC, brgcode commented on src/compas/geometry/primitives/shapes/capsule.py
> +    mesh.to_obj('/Users/bernham/Desktop/capsule.obj')
should this not be a call to `doctest`?

2019-11-05 15:47 UTC, worbit commented on src/compas/geometry/primitives/shapes/capsule.py
> +        matrix : list of list
Agree. I copied this from `primitives.Line` where it is also a matrix and this same docstring. I will go through all the `Shape` classes and update it according to your suggestion.

2019-11-08 10:50 UTC, brgcode commented
@worbit is this thing intentionally still a draft?

2019-11-08 17:03 UTC, worbit commented
no, i think it's good to get merged!

2019-11-09 06:16 UTC, merged