adding base scene implementation
compas-dev/compas pull request #455
Opened 2020-01-13 16:54 UTC by brgcode

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.

### Checklist

1. [ ] Add the change to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading: `Added`, `Changed`, `Removed`.
1. [ ] Run all tests on your computer (i.e. `invoke test`).
1. [ ] If you add new functions/classes, check that:
   1. [ ] Are available on a second-level import, e.g. `compas.datastructures.Mesh`.
   1. [ ] Add unit tests (especially important for algorithm implementations).

2020-01-13 16:55 UTC, brgcode commented
a very simple first version of a scene object.
to do:

- add scene graph
- add naming convention for nodes
- add find function for nodes
- ...

2020-01-14 15:02 UTC, gonzalocasas requested changes
Moving scene/scenenode concepts to core is pretty fundamental to me, the rest is nitpicking.

2020-01-14 15:02 UTC, gonzalocasas commented on src/compas_rhino/scene/scene.py
> +        self.artist = Artist.build(item, **kwargs)
It might be a good thing to move the artist build to be lazily initialized on first usage via a property.

2020-01-14 15:02 UTC, gonzalocasas commented on src/compas_rhino/scene/scene.py
> +class SceneNode(object):
`SceneNode` is completely generic, it should not be on `compas_rhino`, it should be part of core.

2020-01-14 15:02 UTC, gonzalocasas commented on src/compas_rhino/scene/scene.py
> +class Scene(object):
Same here, `Scene` should be a core object, not a Rhino-only. There might be a rhino-specific implementation (or sub-class), but the concept of scene should be present in core.

2020-01-14 15:02 UTC, gonzalocasas commented on src/compas_rhino/scene/scene.py
> +    def save(self, path, width=1920, height=1080, scale=1,
I am not sure `save` a scene is logically the same as screenshoting the current view. I would expect saving a scene means saving all meshes and scene configuration into some file format (like the glTF things that is in progress)

2020-01-14 15:05 UTC, brgcode commented
it is just a temp location, but we can already move it to `compas`. into `compas.scene`?

2020-01-14 15:06 UTC, brgcode commented
or `compas.scenes`

2020-01-15 09:25 UTC, Licini commented on src/compas_rhino/scene/scene.py
> +        self.nodes = []
Shouldn't we have a `parentNode` property?

2020-02-01 07:33 UTC, closed without merging