suggestion: compas_rhino.RobotModelArtist.draw_visual() returns guids
compas-dev/compas pull request #668
Opened 2020-11-13 17:15 UTC by yck011522

It would be useful to have the draw_visual function return the guids of the Native Rhino meshes that was created. This allows higher level code to keep track of the objects being created and allow more refined UI interection via Rhino's UI.

Currently this function returns nothing. The same function in rhino_ghpython returns the actual objects (as gh doesn't actually add geo to doc). So I believe this change is compatible with the overall philosophy.

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

2020-11-16 11:28 UTC, beverlylytle commented on src/compas_rhino/artists/robotmodelartist.py
> +        return guid
It looks like most other compas_rhino `draw` methods return a list of guids even if there's only one (see MeshArtist).  So I think this should be:
```suggestion
        return [guid]
```

2020-11-19 10:44 UTC, yck011522 commented
I'm sick these few days, I'll fix it when I'm back.

2020-12-01 07:46 UTC, gonzalocasas commented
@yck011522 ping ;)
if you merge master back into your branch, the error on the ironpython build will go away.

2020-12-07 11:39 UTC, yck011522 commented
I think this is ready for review.

2020-12-08 11:04 UTC, beverlylytle requested changes

2020-12-08 11:04 UTC, beverlylytle commented on CHANGELOG.md
> +* `compas_rhino.artist.RobotModelArtist` function `draw_visual` and `draw_collision` now returns list of newly created Rhino object guids.
There's some subject-verb disagreement here, so maybe "functions" instead of "function" and "return" instead of "returns".

2020-12-08 11:04 UTC, beverlylytle commented on src/compas_rhino/artists/robotmodelartist.py
> +        """Draws all collision geometry of the robot model. Return list of newly created Rhino object's GUID."""
This isn't quite in the standard format for docstrings. A more consistent version would be ```
"""Draw all the collision geometries of the robot model.

Returns
--------
list 
    The GUIDs of the created Rhino objects.
    
"""```  The same applies to `draw_visual`.

2020-12-08 11:04 UTC, beverlylytle commented on src/compas_rhino/artists/robotmodelartist.py
>          self.draw_visual()
I think to be the same as `draw_visual` it would need to be `return self.draw_visual()`.

2021-01-22 14:38 UTC, beverlylytle approved these changes

2021-01-22 14:38 UTC, beverlylytle commented on CHANGELOG.md
> +* `compas_rhino.artist.RobotModelArtist` function `draw_visual` and `draw_collision` now returns list of newly created Rhino object guids.
```suggestion
* The `compas_rhino.artist.RobotModelArtist` functions `draw_visual` and `draw_collision` now return list of newly created Rhino object guids.
```

2021-01-22 14:38 UTC, beverlylytle commented on src/compas_rhino/artists/robotmodelartist.py
> +        """Draws all visual geometry of the robot model. Return list of newly created Rhino object's GUID."""
```suggestion
        
        """Draw all the visual geometries of the robot model.

        Returns
        -------
        list 
            The GUIDs of the created Rhino objects.
        """
```

2021-01-22 14:38 UTC, beverlylytle commented on src/compas_rhino/artists/robotmodelartist.py
>          self.draw_visual()
```suggestion
        return self.draw_visual()
```

2021-01-22 14:46 UTC, beverlylytle commented on src/compas_rhino/artists/robotmodelartist.py
> +
```suggestion
```

2021-01-22 14:46 UTC, beverlylytle commented on src/compas_rhino/artists/robotmodelartist.py
> +        list
```suggestion
        list
```

2021-01-22 14:46 UTC, beverlylytle commented on src/compas_rhino/artists/robotmodelartist.py
> +        list
```suggestion
        list
```

2021-01-22 14:55 UTC, merged