Complete pluggable trimesh_slice in compas_rhino
compas-dev/compas pull request #870
Opened 2021-06-26 14:56 UTC by XingxinHE

Hi compas team,

I am submitting my PR.

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [x] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

Q: So what is it?
A: It is a simple function which slices the mesh by `Plane`.

2021-06-28 06:12 UTC, beverlylytle requested changes
Hi! Welcome back!  

Thanks for the contribution.  The PR looks pretty good!  There are a few minor comments, but one that needs to be addressed  is line 48 `for vertices, faces in mesh:`. Should have caught that one last time around.

2021-06-28 06:12 UTC, beverlylytle commented on src/compas_rhino/geometry/trimesh/slice.py
> +        for vertices, faces in mesh:
This isn't the structure that is expected for `mesh`.  See https://github.com/compas-dev/compas/blob/aad3e813e6854170c96f0e281f12e708e126340b/src/compas_rhino/geometry/trimesh/curvature.py#L78.

2021-06-28 06:12 UTC, beverlylytle commented on src/compas_rhino/geometry/trimesh/slice.py
> +            P.append(Plane(point, normal))
The attributes of compas Planes are accessible as if they are tuples, so this code could be simplified to:
```suggestion
    for plane in planes:
        point = Point3d(plane[0][0], plane[0][1], plane[0][2])
        normal = Vector3d(plane[1][0], plane[1][1], plane[1][2])
        P.append(Plane(point, normal))
```

2021-06-28 06:12 UTC, beverlylytle commented on src/compas_rhino/geometry/trimesh/slice.py
> +    >>> sphere.to_vertices_and_faces()
Since `Sphere` has a `to_vertices_and_faces` method, this can be simplified:
```suggestion
    >>> sphere = Sphere([1, 1, 1], 1)
    >>> sphere = sphere.to_vertices_and_faces(u=30, v=30)
```

2021-06-28 06:12 UTC, beverlylytle commented on src/compas_rhino/geometry/trimesh/slice.py
> +    if not isinstance(M, Rhino.Geometry.Mesh):
Do you mean:
```suggestion
    if not isinstance(mesh, Rhino.Geometry.Mesh):
```

2021-06-28 06:12 UTC, beverlylytle commented on src/compas_rhino/geometry/trimesh/slice.py
> +    """Slice a mesh by a list of planes.
I think there needs to be a blank line added for the docs to be rendered correctly.
```suggestion
    """Slice a mesh by a list of planes.
    
```

2021-06-28 06:12 UTC, beverlylytle commented on src/compas_rhino/geometry/trimesh/slice.py
> +        The slicing planes.
Here too.
```suggestion
        The slicing planes.
        
```

2021-06-28 15:23 UTC, XingxinHE commented
> Hi! Welcome back!
> 
> Thanks for the contribution. The PR looks pretty good! There are a few minor comments, but one that needs to be addressed is line 48 `for vertices, faces in mesh:`. Should have caught that one last time around.

2021-06-28 15:25 UTC, XingxinHE commented on src/compas_rhino/geometry/trimesh/slice.py
> +        for vertices, faces in mesh:
Hi Dr. Lytle,

thx for the feedback. I checked the history... It seems Dr. Van Mele removed the for loop.  Sorry I didn't notice this. Will fix!

2021-06-28 15:48 UTC, XingxinHE commented on src/compas_rhino/geometry/trimesh/slice.py
> +            P.append(Plane(point, normal))
Good to know!

2021-06-30 07:52 UTC, beverlylytle approved these changes
LGTM!

2021-06-30 07:53 UTC, merged