Add Halfface element queries
compas-dev/compas pull request #911
Opened 2021-10-07 16:06 UTC by Sam-Bouten

Included queries (_where and _where_predicate) for elements of VolMesh (halfface.py),
that up until now were placeholders or had no interface declared.
Consistent with the Mesh datastructure (halfedge.py) query functions.

resolves issue #906.

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

- [x] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

2021-10-08 06:53 UTC, tomvanmele reviewed
this seems very testable. please add some :)

2021-10-08 06:53 UTC, tomvanmele commented on src/compas/datastructures/halfface/halfface.py
> +            The condition you want to evaluate. The callable takes 2 parameters: ``key``, ``attr`` and should return ``True`` or ``False``.
just fyi.
i personally prefer "vertical code".
so i would split these two sentences over two lines...

2021-10-08 07:09 UTC, beverlylytle commented on src/compas/datastructures/halfface/halfface.py
> +            The condition you want to evaluate. The callable takes 2 parameters: ``key``, ``attr`` and should return ``True`` or ``False``.
This seems like a thing the linter should catch.  Would it make sense to reduce the `max-line-length` from `180`?

2021-11-02 09:10 UTC, brgcode requested changes
generally looking good, but could you add a few test?

2022-02-23 13:19 UTC, gonzalocasas commented
@brgcode could you pls take a look at this again and confirm if it's good to go?

2022-02-23 14:48 UTC, brgcode requested changes

2022-02-23 14:48 UTC, tomvanmele commented on src/compas/datastructures/halfface/halfface.py
> +        halfface = data.get('halfface') or {}
why are you adding this? it is redundant information...

2022-02-23 14:48 UTC, tomvanmele commented on src/compas/datastructures/halfface/halfface.py
> +            self.add_halfface(halfface[f], fkey=int(f), attr_dict=attr)
why?

2022-02-23 14:48 UTC, tomvanmele commented on src/compas/datastructures/halfface/halfface.py
> +                    faces.append(halfface[str(f)])
why?

2022-02-23 14:48 UTC, tomvanmele commented on src/compas/datastructures/halfface/halfface.py
> +    def key_index(self):
it should be `vertex_index`. `key` is a reference to the internal storage mechanism, which should not be exposed to the user. in the other data structures both variants exist, but only to preserve backward compatibility...

2022-02-23 14:48 UTC, tomvanmele commented on src/compas/datastructures/halfface/halfface.py
> +            A dictionary of key-index pairs.
they are, in fact, "vertex-index" pairs

2022-02-23 14:48 UTC, tomvanmele commented on src/compas/datastructures/halfface/halfface.py
> +    def index_key(self):
same

2022-02-23 14:48 UTC, tomvanmele commented on src/compas/datastructures/halfface/halfface.py
> +            A dictionary of index-key pairs.
same

2022-02-23 14:49 UTC, brgcode commented
> @brgcode could you pls take a look at this again and confirm if it's good to go?

it never was, but i seem to have forgotten to submit my review...

2022-02-23 16:02 UTC, Sam-Bouten commented on src/compas/datastructures/halfface/halfface.py
> +        halfface = data.get('halfface') or {}
iirc added this because of getting bugs initializing Volmeshes certain ways (all changes in commit 1d9b6c).
will remove it from this PR and look into it again separately.

2022-02-23 16:03 UTC, Sam-Bouten commented on src/compas/datastructures/halfface/halfface.py
> +            self.add_halfface(halfface[f], fkey=int(f), attr_dict=attr)
same (commit 1d9b6c).

2022-02-23 16:03 UTC, Sam-Bouten commented on src/compas/datastructures/halfface/halfface.py
> +                    faces.append(halfface[str(f)])
same (commit 1d9b6c).

2022-02-23 20:07 UTC, brgcode requested changes

2022-02-23 20:07 UTC, tomvanmele commented on src/compas/datastructures/halfface/halfface.py
> +                faces.append(cell[c][u][v])
why is this loop removed? this cannot possibly be expected to yield the same result...

2022-02-23 20:07 UTC, tomvanmele commented on src/compas/datastructures/halfface/halfface.py
> +        keys in a vertex dictionary.
should be "the", since it refers to "the" vertex dictionary used for internal storage, not "a" random vertex dictionary

2022-02-23 20:07 UTC, brgcode commented on src/compas/datastructures/halfface/halfface.py
> +            The next vertex and its attributes, if ``data=True``.
this format indicates that two items will be returned: a hashable, and a tuple with two elements. this is however not the case. either a hashable is returned, or a hashable and a tuple with two elements. the correct format is therefore
```
hashable | tuple[hashable, dict[str, Any]]
    If `data` is False, the next vertex identifier.
    If `data` is True, the next vertex identifier and the vertex attributes.
```

2022-02-23 20:07 UTC, brgcode commented on src/compas/datastructures/halfface/halfface.py
> +            The next vertex and its attributes, if ``data=True``.
same comment

2022-02-23 20:07 UTC, brgcode commented on src/compas/datastructures/halfface/halfface.py
> +            The next edge as a (u, v, data) tuple, if ``data=True``.
same + leave 1 blank line at end of docstring

2022-02-23 20:07 UTC, brgcode commented on src/compas/datastructures/halfface/halfface.py
> +            The next edge as a (u, v, data) tuple, if ``data=True``.
same

2022-02-23 20:07 UTC, tomvanmele commented on src/compas/datastructures/halfface/halfface.py
> +        """
blank line

2022-02-23 20:07 UTC, brgcode commented on src/compas/datastructures/halfface/halfface.py
> +            The next face and its attributes, if ``data=True``.
same

2022-02-23 20:07 UTC, brgcode commented on src/compas/datastructures/halfface/halfface.py
> +            The next face and its attributes, if ``data=True``.
same

2022-02-23 20:07 UTC, brgcode commented on src/compas/datastructures/halfface/halfface.py
> +        """
same

2022-02-23 20:07 UTC, brgcode commented on src/compas/datastructures/halfface/halfface.py
> +            The next cell and its attributes, if ``data=True``.
same

2022-02-23 20:07 UTC, brgcode commented on src/compas/datastructures/halfface/halfface.py
> +            The next cell and its attributes, if ``data=True``.
same

2022-02-23 20:07 UTC, brgcode commented on src/compas/datastructures/halfface/halfface.py
> +        >>>
perhaps we should also not include any more empty examples :)

2022-02-23 20:34 UTC, Sam-Bouten commented on src/compas/datastructures/halfface/halfface.py
> +                faces.append(cell[c][u][v])
wrongly left out one loop when changing halfface data init, reverted this to main now.

2022-02-23 20:34 UTC, Sam-Bouten commented on src/compas/datastructures/halfface/halfface.py
> +        keys in a vertex dictionary.
ok, shall we update the same in docstring of halfedge key_index() method.

2022-02-23 21:15 UTC, brgcode commented
@Sam-Bouten can you update your `main` and merge it into the PR again? it will solve the failed docs workflow...

2022-02-24 09:02 UTC, brgcode reviewed
can you remove the double backticks from the docstrings, please?
reference to a parameter name is 
```
`param`
```
and True and False are without anything...

2022-02-24 09:02 UTC, brgcode approved these changes

2022-02-24 09:02 UTC, merged