Artist subclass
compas-dev/compas pull request #917
Opened 2021-10-26 16:43 UTC by beverlylytle

Some classes subclass classes with artists.  For example, `Origin` is essentially a `Frame`, and should be drawn as such.

### What type of change is this?

- [x] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

2021-10-26 18:41 UTC, tomvanmele commented on src/compas_blender/artists/__init__.py
> +                break
i think this can be problematic because it doesn't respect class hierarchy.

for example, consider `FormDiagram` which is a sub class of `Mesh` and is registered with a `FormDiagramArtist` that provides more specific visualisation functionality than `MeshArtist`. there is nothing in this loop that gives precedence to `FormDiagramArtist` over `MeshArtist`.

not sure if it would solve the problem entirely, but perhaps checking for direct registration before running the loop could help.

```python
if dtype in BlenderArtist.ITEM_ARTIST:
    cls = BlenderArtist.ITEM_ARTIST[dtype]
else:
    for type_ in BlenderArtist.ITEM_ARTIST:
        if issubclass(dtype, type_):
            cls = BlenderArtist.ITEM_ARTIST[type_]
            break
```

2021-10-26 23:32 UTC, gonzalocasas approved these changes
LGTM, but I would definitely like to have one or two unit tests to check for this sub-class matching. And if you're feeling inspired, refactoring the repetitive code that we already have in place for the `new_artist` stuff into a more general location would be ideal, but if not, we can also leave it for another PR.

2021-10-26 23:32 UTC, gonzalocasas commented on src/compas_blender/artists/__init__.py
> +            raise DataArtistNotRegistered('No GH artist is registered for this data type: {}'.format(dtype))
```suggestion
            raise DataArtistNotRegistered('No Blender artist is registered for this data type: {}'.format(dtype))
```

2021-10-26 23:32 UTC, gonzalocasas commented on src/compas_rhino/artists/__init__.py
> +            raise DataArtistNotRegistered('No GH artist is registered for this data type: {}'.format(dtype))
```suggestion
            raise DataArtistNotRegistered('No Rhino artist is registered for this data type: {}'.format(dtype))
```

2021-10-27 05:13 UTC, tomvanmele requested changes
sorry, but we need to at least first have a discussion about the class hierarchy thing. my concern was not really hypothetical. the formdiagram example is a real case...

2021-10-27 13:56 UTC, beverlylytle commented on src/compas_blender/artists/__init__.py
> +                break
I take your point, but where does `FormDiagram` exist?  I guess there should be tests or examples somewhere about registering external artists.

2021-10-27 14:02 UTC, tomvanmele commented on src/compas_blender/artists/__init__.py
> +                break
`FormDiagram` exists in `compas_tna` but it applies to any artist type that builds upon a base artist. there are many such cases in `compas_assembly`, `compas_ags`, `compas_fofin`, ...

perhaps we can set up an artificial test where we make a custom mesh class which is registered to a custom mesh artist and check if the correct type of artist is indeed constructed?

2021-10-27 23:25 UTC, gonzalocasas commented
@brgcode we now are handling correctly the type hierarchy with the latest change by @beverlylytle ... 
Re-review?

2021-10-28 06:19 UTC, tomvanmele approved these changes
very nice!

2021-10-28 13:02 UTC, merged